### ISSUE TITLE
Get Device State (Blue/Red/Yellow lights)

### ISSUE THREAD

**Issue by gravesjohnr** [adafruit/Adafruit_BLESniffer_Python#6]
Normally, when I start the sniffer.py and connect, the device goes through a cycle of blue flashing (I assume 'ready') and yellow flashing (I assume scanning) and red is off.  Once connected, I get red and yellow flashing (connected).   When the other device connects, I get all three lights flashing, blue yellow red.

But, sometimes, the python script things it has connected, but I continue to get a blue/yellow flashing and it never really connects.  The only way I can fix this is to restart the code.  I'd like to re-run the setup in this case, but I can't tell when it gets into this state.  I even get packets in the dumpPackets code.

Is there a way to get a status from the device regarding these LEDs?  I would then be able to programmatically reset things.

Thanks.

**Comment by ladyada** [comment]
no idea - the firmware is not open source, it comes direct to us from nordic - we just burn it in since its the same chipset! 
https://www.nordicsemi.com/eng/Products/Bluetooth-Smart-Bluetooth-low-energy/nRF-Sniffer
for more details.
you'll probably just have to re-run it till it works!
